# Generated by Django 4.0.6 on 2024-04-29 02:59

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('original_content', models.TextField(blank=True)),
                ('positional_index', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
